# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Soutien scolaire - Maths
email: rbr.prof@gmail.com
tagline: Les maths chez vous
description: >- # this means to ignore newlines until "baseurl:"
  Besoin de cours de maths en ligne?
  Grâce aux nouvelles technologies, il n'est plus nécessaire d'avoir à sortir de chez-soi pour profiter de l'expertise d'un professeur.
logo: /assets/img/logo-256.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tucorib.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: fr_FR
webmaster_verifications:
  google: Da7MELhhJqTEsd2kgrrY5krNiZdyzx1LT24evhTmdmA
  
social:
  name: Nicolas Ribeiro
github_username:  tucorib
  
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-include_sass
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

language: "fr"
future: false
sass:
    sass_dir: _includes/scss
    style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "empty"

imgcache: "https://tucorib-github-io.cdn.ampproject.org/i/tucorib.github.io"

device:
  sm: "(max-width: 768px)"
  xl: "(min-width: 768px)"
  
home:
  carousel:
    delay: 8000
    height_sm: 377
    height_xl: 250
  youtube:
      width: 560
      height: 315
      autoplay: false
      